#%RAML 1.0 Trait
usage: Proudct api trait

headers:
  Content-Type: 
   required: false
   type: string
   example: application/json
  X-correaltion-id:
   required: false
   type: string
   example: eyJhGcioiJIUzI1NiIsInR5c
